# Pingus - A free Lemmings clone
# Copyright (C) 2015 Ingo Ruhnke <grumbel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Build file for https://travis-ci.org/
#
# Configuration manual:
# http://docs.travis-ci.com/user/build-configuration/
#
# Based on:
# https://github.com/supertuxkart/stk-code/blob/master/.travis.yml
# https://github.com/SuperTux/supertux/blob/master/.travis.yml

language: cpp
dist: trusty
sudo: required

compiler:
  - gcc
  - clang

matrix:
  fast_finish: true
  exclude:
  - compiler: gcc
    os: osx

os:
  - linux
  # - osx

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "CPJBu4r8RDmeP7G78ODyk+A/J3vxEFr4xpQE0zIDtdCHcQmv2NqjM88YVH5pRWK4vtpAFuDEzyw4ZGKwfmwK5zhg2nUubsf47WpQmQa0z9HLasjXATzWwXGggx7mzlKODpkkccBzXHDAqvLKTkKBeXdxwMKFCtSgEM+3MwEwW6g="
  matrix:
    - BUILD_TYPE="Debug"
    - BUILD_TYPE="Release"

before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-5.0"; fi

script:
  # Clean from previous Travis build
  - git clean -f
  # Then build:
  - mkdir "build-$BUILD_TYPE"
  - cd "build-$BUILD_TYPE"
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS=ON -DWERROR=ON -DBUILD_TESTS=ON -DBUILD_EXTRA=ON
  - make VERBOSE=1
  - make VERBOSE=1 install DESTDIR=/tmp/pingus-${BUILD_TYPE}
  - (cd .. && build-${BUILD_TYPE}/test_pingus)

# The branch coverity_scan is used to trigger the start of a coverity
# scan, merge the latest development version into and push it to start
# the scan.
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - clang-5.0
    - g++-4.9
    - cmake
    - build-essential
    - libc++-dev
    - libogg-dev
    - libvorbis-dev
    - libglew-dev
    - libopenal-dev
    - libboost-all-dev
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - libjsoncpp-dev
  coverity_scan:
    project:
      name: "Pingus/pingus"
      description: "Build submitted via Travis CI"
    notification_email: grumbel@gmail.com
    build_command_prepend: "cmake . && make clean"
    build_command: "make"
    branch_pattern: coverity_scan

# EOF #
